{% set name = "gmaps" %}
{% set version = "0.8.3" %}
{% set sha256 = "639bea8f1bcdf9ab422e5bf34303bcf12c69012fcab99132c4d3d8dd55238baf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - jupyter
  run:
    - python
    - ipywidgets >=7.0.0
    - geojson >=2.0.0

test:
  imports:
    - gmaps

about:
  home: http://github.com/pbugnion/gmaps
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Google maps for Jupyter notebooks'
  description: |
    gmaps is a Jupyter plugin for visualizing data on Google maps in Jupyter notebooks.
  doc_url: http://jupyter-gmaps.readthedocs.io/
  dev_url: https://github.com/pbugnion/gmaps

extra:
  recipe-maintainers:
    - pbugnion
